// アプリ独自 Tauri command の一覧。`lib.rs` と `build.rs` の唯一の定義。
//
// このファイルは `build.rs` から `include!` される。そのため
//
// - 依存 crate を使う `use` を書いてはいけない、
// - モジュールドキュメント (`//!`) を書いてはいけない
//   (`include!` の展開位置には inner attribute を置けない。説明は `lib.rs` の
//   `pub mod app_commands;` 側に書く)、
//
// という 2 つの制約がある。テスト (`#[cfg(test)]`) はビルドスクリプトでは
// 取り除かれるので、ここに置いてよい。

/// アプリ独自 Tauri command の完全な一覧。
///
/// `lib.rs` の `tauri::generate_handler!` と **1 対 1 で一致させること**。
/// `build.rs` がこれを `tauri_build::AppManifest::commands` へ渡し、
/// `allow-<command>` / `deny-<command>` の permission を
/// `permissions/autogenerated/` に生成する。生成された permission は
/// `capabilities/*.json` でウィンドウごとに割り当てる。
///
/// ここから漏れた command は permission が生成されず、
/// **どのウィンドウからも invoke できなくなる**。
pub const APP_COMMANDS: &[&str] = &[
    // タスク操作
    "get_board",
    "get_task",
    "create_task",
    "update_task",
    "move_task",
    "complete_task",
    "promote_task",
    "add_task_update",
    "add_resource",
    "remove_resource",
    "set_parent",
    // ソフトデリート(main ウィンドウ専用)
    "delete_task",
    "restore_task",
    "list_deleted_tasks",
    // 設定・稼働状態・ウィンドウ
    "get_settings",
    "get_default_settings",
    "set_settings",
    "get_runtime_status",
    "show_main_window",
    // 内蔵ブラウザペイン(main ウィンドウ専用)
    "browser_pane_open",
    "browser_pane_close",
    "browser_pane_set_bounds",
    "browser_pane_set_visible",
    // MCP トークン(値は返さない。main ウィンドウ専用)
    "get_mcp_token_status",
    "set_mcp_token",
    // AI
    "ai_create_tasks",
    "ai_split_task",
    "ai_free_instruction",
    "ai_cancel",
    // プラグイン基盤
    "plugin_directory",
    "plugin_list_sources",
    "plugin_kv_get",
    "plugin_kv_set",
    "plugin_kv_keys",
    "plugin_get_settings",
    "plugin_set_settings",
    "plugin_list_task_resources",
    "plugin_log",
    "plugin_fetch_allowed",
    "plugin_publish_loaded",
    "plugin_list_loaded",
    // プラグインのシークレット。読み出しは plugin-host のみ、
    // 書き込みと状態確認は設定画面(main)のみに配る。
    "plugin_secret_get",
    "plugin_secret_set",
    "plugin_secret_status",
];

/// command 名から、`build.rs` が生成する許可 permission の識別子を作る。
///
/// 生成規則は `tauri_utils::acl::build::autogenerate_command_permissions` に合わせ、
/// `_` を `-` に置き換えて `allow-` を付けるだけ。
#[must_use]
pub fn allow_permission(command: &str) -> String {
    format!("allow-{}", command.replace('_', "-"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn app_commands_are_unique_and_snake_case() {
        let mut sorted = APP_COMMANDS.to_vec();
        sorted.sort_unstable();
        let before = sorted.len();
        sorted.dedup();
        assert_eq!(sorted.len(), before, "command 名が重複している");

        for command in APP_COMMANDS {
            assert!(
                command
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_'),
                "{command} は snake_case ではない"
            );
        }
    }

    #[test]
    fn permission_identifiers_use_dashes() {
        assert_eq!(allow_permission("get_board"), "allow-get-board");
        assert_eq!(allow_permission("plugin_kv_set"), "allow-plugin-kv-set");
    }
}
