//! Tauri のビルドスクリプト。
//!
//! 既定の `tauri_build::build()` はアプリ独自 command の permission を作らないため、
//! 独自 command は ACL の対象外になり、**どのウィンドウからでも invoke できてしまう**
//! (plugin-host / overlay から `set_settings` や `ai_*` が呼べる状態)。
//!
//! そこで `AppManifest::commands` にアプリ独自 command を渡し、
//! `permissions/autogenerated/<command>.toml` に `allow-<command>` / `deny-<command>` を
//! 生成させる。生成した permission を `capabilities/*.json` でウィンドウごとに割り当てると、
//! Tauri が invoke のたびに ACL を評価するようになる。
//!
//! command の一覧は `src/app_commands.rs` の `APP_COMMANDS` が唯一の定義で、
//! `lib.rs` の `tauri::generate_handler!` と共有する。

// 依存 crate を使わない定数だけのファイルなので、ビルドスクリプトからも読める。
// ここで使うのは APP_COMMANDS だけ(残りは lib 側で使う)。
#[allow(dead_code)]
mod app_commands {
    include!("src/app_commands.rs");
}

use app_commands::APP_COMMANDS;

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("Tauri のビルド設定に失敗しました");
}
